version: '3'
services:
  webserver:
    container_name: ${PHP_CONTAINER_NAME}
    hostname: ${PHP_CONTAINER_NAME}
    restart: unless-stopped
    build: ${PHP_PATH}
    volumes:
      - ${SITES_PATH}:/var/www
      - ${PHP_PATH}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${PHP_PATH}/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ${PHP_PATH}/php/php.ini:/etc/php81/conf.d/settings.ini
      - ${PHP_PATH}/php/www.conf:/etc/php8/php-fpm.d/www.conf
      - ${STORAGE_ROOT_PATH}/PHP/nginx:/var/log/nginx
      - ${STORAGE_ROOT_PATH}/PHP/php81:/var/log/php81
    working_dir: /var/www
    ports:
      - 8080:8080

  mysql:
    image: mysql:8.1
    container_name: ${MYSQL_CONTAINER_NAME}
    hostname: ${MYSQL_CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - ${STORAGE_ROOT_PATH}/MySQL:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  adminer:
    image: adminer:latest    
    container_name: ${ADMINER_CONTAINER_NAME}
    hostname: ${ADMINER_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: ${MYSQL_CONTAINER_NAME}
    ports:
      - 8090:8080

  node:
    container_name: NODEJS_SERVER
    build: ${NODEJS_PATH}
    restart: unless-stopped
    volumes:
      - ${SITES_PATH}:/var/www
    tty: true
    working_dir: /var/www
    ports:
      - 3000:3000
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ${RABBIT_MQ_CONTAINER_NAME}
    hostname: ${RABBIT_MQ_CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - ${STORAGE_ROOT_PATH}/RabbiMq:/var/lib/rabbitmq
    environment:
     - RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_PASS}
     - RABBITMQ_DEFAULT_USER=${RABBIT_MQ_USER}
    ports:
      - 9090:15672 # Redis Management Panel
      - 9091:5672 # Redis port
    
  redis:
    image: redis:latest    
    container_name: ${REDIS_CONTAINER_NAME}
    hostname: ${REDIS_CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - ${STORAGE_ROOT_PATH}/Redis:/data

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${STORAGE_ROOT_PATH}/Portainer/data:/data
